modLoader="javafml" #mandatory

loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="2020 | SP UNIVERSE | ALL RIGHTS RESERVED"

issueTrackerURL="https://github.com/Steven-Paw-Design/awesomeshop/issues" #optional

[[mods]] #mandatory

modId="awesomeshop" #mandatory

version="1.16.4-0.1.0beta" #mandatory

displayName="Awesome Shop" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://sp-universe.com/" #optional

logoFile="awesomeshop-logo.png" #optional

credits="Thanks for this Mod goes to my girlfriend. With her beautiful ideas #optional

authors="Steven Paw - SP Universe" #optional

description='''
This is a mod about a shop that fuels with trash

Make great things with garbage and have fun!
'''