modLoader="javafml" #mandatory

loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="CC BY-NC 3.0 DE"

issueTrackerURL="https://github.com/Steven-Paw-Design/awesomeshop/issues" #optional

[[mods]] #mandatory
modId="awesomeshop" #mandatory
version="1.16.4-1.1.0" #mandatory
displayName="Awesome Shop" #mandatory
updateJSONURL="https://github.com/Steven-Paw-Design/awesomeshop/blob/develop/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/awesome-shop" #optional
logoFile="awesomeshop-logo.png" #optional
#credits="Thanks for this Mod goes to my girlfriend. With her beautiful ideas" #optional
authors="Steven Paw Design" #optional
description='''
This Mod adds Awesomnium, Depressnium and Ducatium into the Game to make decorative things.
With the won Awesomnium you can create more Deco Blocks for your house and a few useful items.
'''

[[dependencies.awesomeshop]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.awesomeshop]] #optional
    modId="minecraft" #mandatory
    mandatory=true #mandatory
    versionRange="[1.16.4]" #mandatory
    ordering="NONE"
    side="BOTH"